maintainer        "CrowdMob Inc."
maintainer_email  "developers@crowdmob.com"
license           "Apache 2.0"
description       "Install CrowdMob's redshift-tracking-copy-from-s3, configure with databag, and run with monit."
version           "0.0.1"
recipe            "redshift-tracking-copy-from-s3::install"
recipe            "redshift-tracking-copy-from-s3::run"
depends           "golang"
depends           "monit"
